import fs from "fs";
import path from "path";
import type { TestSuggestion } from "./types";

const REVIEW_HEADER = `/**
 * GENERATED BY KAMU WEB AUDIT - AI PROVIDER
 * REVIEW REQUIRED: Do not run in CI without human review.
 * These are suggestions only; validate selectors and flows before use.
 */
`;

/**
 * Writes suggested test skeletons to runDir/generated/tests/ and a REVIEW_REQUIRED notice.
 */
export function writeGeneratedTests(runDir: string, suggestions: TestSuggestion[]): string[] {
  const outDir = path.join(runDir, "generated", "tests");
  fs.mkdirSync(outDir, { recursive: true });
  const written: string[] = [];

  for (const s of suggestions) {
    const safeName = s.gapElementId.replace(/[^a-zA-Z0-9-_]/g, "_").slice(0, 40);
    const filePath = path.join(outDir, `gap-${safeName}.spec.ts`);
    const content = REVIEW_HEADER + "\n" + s.scriptContent;
    fs.writeFileSync(filePath, content, "utf-8");
    written.push(filePath);
  }

  if (suggestions.length > 0) {
    const noticePath = path.join(outDir, "REVIEW_REQUIRED.txt");
    fs.writeFileSync(
      noticePath,
      "Generated test skeletons require human review before execution in CI.\nDo not auto-run these files.\n",
      "utf-8"
    );
    written.push(noticePath);
  }

  return written;
}
