// <auto-generated />
using System;
using System.Text.Json;
using KamuAudit.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KamuAudit.Api.Migrations
{
    [DbContext(typeof(KamuAuditDbContext))]
    [Migration("20260306064646_AddAuditRunLeasing")]
    partial class AddAuditRunLeasing
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditCoverage", b =>
                {
                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<double>("CoverageRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("SkippedElements")
                        .HasColumnType("integer");

                    b.Property<int>("TestedElements")
                        .HasColumnType("integer");

                    b.Property<int>("TotalElements")
                        .HasColumnType("integer");

                    b.HasKey("AuditRunId");

                    b.ToTable("audit_coverage", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Browser")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<long?>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LeaseVersion")
                        .HasColumnType("integer");

                    b.Property<int?>("LinkBroken")
                        .HasColumnType("integer");

                    b.Property<int?>("LinkSampled")
                        .HasColumnType("integer");

                    b.Property<int>("MaxLinks")
                        .HasColumnType("integer");

                    b.Property<int>("MaxUiAttempts")
                        .HasColumnType("integer");

                    b.Property<string>("Plugins")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("RetryAfterUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RunDir")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("SafeMode")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("Strict")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("SystemId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LeaseUntil");

                    b.HasIndex("Status");

                    b.HasIndex("SystemId");

                    b.HasIndex("UserId");

                    b.ToTable("audit_runs", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditTargetCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("EncryptedPassword")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)");

                    b.Property<string>("TwoFactorNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId")
                        .IsUnique();

                    b.ToTable("audit_target_credentials", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.ElementHistory", b =>
                {
                    b.Property<string>("ElementHash")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer");

                    b.Property<int>("PassCount")
                        .HasColumnType("integer");

                    b.HasKey("ElementHash");

                    b.ToTable("element_history", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.Finding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double?>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<string>("Remediation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.ToTable("findings", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.FindingInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FindingTemplateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.HasIndex("FindingTemplateId");

                    b.ToTable("finding_instances", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.FindingTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoRiskLowerSuggested")
                        .HasColumnType("boolean");

                    b.Property<string>("CanonicalUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<JsonDocument>("Meta")
                        .HasColumnType("jsonb");

                    b.Property<long>("OccurrenceCount")
                        .HasColumnType("bigint");

                    b.Property<string>("Parameter")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RecentSafeOccurrences")
                        .HasColumnType("integer");

                    b.Property<string>("Remediation")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.ToTable("finding_templates", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.Gap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionHint")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ElementId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<JsonDocument>("Evidence")
                        .HasColumnType("jsonb");

                    b.Property<string>("HumanName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RecommendedScript")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.ToTable("gaps", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.GapTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExampleUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("HumanName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("ReasonCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.ToTable("gap_templates", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AuditRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AuditRunId");

                    b.HasIndex("UserId", "Key")
                        .IsUnique();

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.SystemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("systems", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditCoverage", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithOne()
                        .HasForeignKey("KamuAudit.Api.Domain.Entities.AuditCoverage", "AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditRun", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.SystemEntity", "System")
                        .WithMany("AuditRuns")
                        .HasForeignKey("SystemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("KamuAudit.Api.Domain.Entities.User", "User")
                        .WithMany("AuditRuns")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("System");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditTargetCredential", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithOne()
                        .HasForeignKey("KamuAudit.Api.Domain.Entities.AuditTargetCredential", "AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.Finding", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("Findings")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.FindingInstance", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KamuAudit.Api.Domain.Entities.FindingTemplate", "FindingTemplate")
                        .WithMany()
                        .HasForeignKey("FindingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");

                    b.Navigation("FindingTemplate");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.Gap", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany("Gaps")
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.GapTemplate", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.IdempotencyKey", b =>
                {
                    b.HasOne("KamuAudit.Api.Domain.Entities.AuditRun", "AuditRun")
                        .WithMany()
                        .HasForeignKey("AuditRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KamuAudit.Api.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuditRun");

                    b.Navigation("User");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.AuditRun", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Gaps");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.SystemEntity", b =>
                {
                    b.Navigation("AuditRuns");
                });

            modelBuilder.Entity("KamuAudit.Api.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditRuns");
                });
#pragma warning restore 612, 618
        }
    }
}
